### List all messages
GET http://localhost:3000/messages

### Get specific message
GET http://localhost:3000/messages/123


### Create new message
POST http://localhost:3000/messages
Content-Type: application/json

{
    "content": true
}


### Create user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123"
}

### Get user by ID
GET http://localhost:3000/auth/5

### Update user

PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "mindev48@gmail.com"
}

### Delete user

DELETE http://localhost:3000/auth/1

### Get all users

GET http://localhost:3000/auth